# Generated by Django 5.0.1 on 2024-03-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='billing_address',
            new_name='town_address',
        ),
    ]
