# Generated by Django 5.0.1 on 2024-03-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_billing_address_checkout_town_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='payment_option',
        ),
    ]
