# Generated by Django 5.0.1 on 2024-03-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_checkout_payment_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='town_address',
            new_name='shipping_address',
        ),
    ]
