# Generated by Django 5.0.1 on 2024-03-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_town_address_address_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='town_address',
            new_name='Checkouts',
        ),
    ]
