# Generated by Django 5.0.1 on 2024-03-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_checkouts_checkout_town_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='shipping_address',
            new_name='town_address',
        ),
    ]
