# Generated by Django 5.0.1 on 2024-03-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_reference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='save_info',
        ),
    ]
