# Generated by Django 5.0.1 on 2024-05-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_track_order_trackorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackorder',
            name='reference_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
