# Generated by Django 5.0.1 on 2024-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_trackorder_reference_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackorder',
            name='reference_code',
        ),
        migrations.AddField(
            model_name='trackorder',
            name='status_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trackorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
