# Generated by Django 5.0.1 on 2024-05-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_trackorder_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackorder',
            name='courier_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackorder',
            name='on_the_way_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackorder',
            name='ready_for_pickup_approved',
            field=models.BooleanField(default=False),
        ),
    ]
